ARG BASE_CONTAINER=ubuntu:18.04
FROM $BASE_CONTAINER

MAINTAINER Morpheus9631 (morpheus.hsieh@gmail.com)

# Fix DL4006
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Update, Upgrade and Install packages
USER root
RUN echo 'root:1234' | chpasswd

# Add new user
ARG NB_USER=user
RUN useradd -G sudo -m -s /bin/bash $NB_USER
RUN echo "$NB_USER:1234" | chpasswd

# Install all depencies
RUN apt-get update && apt-get install -y --no-install-recommends\
 openssh-server sudo nano wget\
 && apt-get clean\
 && rm -rf /var/lib/apt/lists/*

# Install Nvidia repository
#

RUN apt-get update && apt-get install -y --no-install-recommends\
 gnupg2 curl ca-certificates \
 && curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | apt-key add -\
 && echo 'deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /' > /etc/apt/sources.list.d/cuda.list\
 && echo 'deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /' > /etc/apt/sources.list.d/nvidia-ml.list\
 && rm -rf /var/lib/apt/lists/*

ENV CUDA_VERSION 10.1.243

# Install Nvidia cuda
# For libraries in the cuda-compat-* package,
# see https://docs.nvidia.com/cuda/eula/index.html#attachment-a
#
RUN apt-get update && apt-get install -y --no-install-recommends\
 cuda-cudart-10-1=$CUDA_VERSION-1\
 cuda-compat-10-1\
 && ln -s cuda-10.1 /usr/local/cuda\
 && rm -rf /var/lib/apt/lists/*

# Required for nvidia-docker v1
RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf &&\
 echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

# Setup environment variable

ENV CUDA_PATH /usr/local/nvidia/bin:/usr/local/cuda/bin
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411"

# Setup environment variables for all user
RUN echo -e 'export CUDA_VERSION="'$CUDA_VERSION'"' >> /etc/profile
RUN echo -e 'export PATH="'$CUDA_PATH':$PATH"' >> /etc/profile
RUN echo -e 'export LD_LIBRARY_PATH="'$LD_LIBRARY_PATH'"' >> /etc/profile
RUN echo -e 'export NVIDIA_VISIBLE_DEVICES="'$NVIDIA_VISIBLE_DEVICES'"' >> /etc/profile
RUN echo -e 'export NVIDIA_DRIVER_CAPABILITIES="'$NVIDIA_DRIVER_CAPABILITIES'"' >> /etc/profile
RUN echo -e 'export NVIDIA_REQUIRE_CUDA="'$NVIDIA_REQUIRE_CUDA'"' >> /etc/profile


# Install SSH service
RUN mkdir -p /var/run/sshd
RUN sed -i 's/#\?PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#\?PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/#\?PermitEmptyPasswords no/PermitEmptyPasswords no/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

ARG WORK_DIR=work
RUN mkdir /home/$NB_USER/$WORK_DIR
RUN chown $NB_USER:$NB_USER /home/$NB_USER/$WORK_DIR

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

