ARG BASE_CONTAINER=morpheus9631/cuda:10.1-devel
FROM $BASE_CONTAINER

MAINTAINER Morpheus9631 (morpheus.hsieh@gmail.com)

ENV CUDNN_VERSION 7.6.5.32

# Install Nvidia cudnn7
RUN apt-get update && apt-get install -y --no-install-recommends\
 libcudnn7=$CUDNN_VERSION-1+cuda10.0\
 libcudnn7-dev=$CUDNN_VERSION-1+cuda10.0 &&\
 apt-mark hold libcudnn7 &&\
 rm -rf /var/lib/apt/lists/*

RUN echo 'export CUDNN_VERSION="'$CUDNN_VERSION'"' >> /etc/profile
